# https://blog.simos.info/tag/snapcraft-yaml/

name: lindacoin-wallet
version: '0.1'
summary: Cryptocurrency Wallet for LindaCoin
description: |
    Linda Cryptocoin is a hybrid coin with more than 70% pure PoS Block reward phase and 99% APR. This coin comes with a masternode which ensures lightening fast secured transaction, multi-wallets, encrypted messaging and stealth address for complete anonymity.

grade: stable
confinement: strict 
icon: lindacoin-wallet1.png

apps:
  lindacoin-wallet:
    command: desktop-launch $SNAP/Linda-qt
    plugs:
      - network
      - network-bind
      - x11
      - home
      - unity7


parts:
  lindacoin-wallet:
    plugin: qmake
    source: https://github.com/Lindacoin/Linda.git
    options: ["USE_UPNP=-"]
    qt-version: "qt5"
    install:
      mv ../build/Linda-qt $SNAPCRAFT_PART_INSTALL
    build-packages:
      - libssl-dev
      - libgmp3-dev 
      - libevent-dev 
      - bsdmainutils 
      - libboost-all-dev
    stage-packages:
      - libboost-all-dev
    after:
      - desktop-qt5
      - libdb
      - secp256k1 

  libdb:
    plugin: autotools
    source: http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
    #source-subdir: build_unix 
    #configflags: ["--enable-cxx"]
    build: |
      cd ./build_unix
      ../dist/configure --enable-cxx
      make
      sudo make install
    artifacts:
      - libdb_cxx-4.8.so
      - libdb-4.8.so

  secp256k1:
    plugin: autotools
    source: https://github.com/Lindacoin/Linda.git
    source-subdir: src/secp256k1
    artifacts:
      - .libs/libsecp256k1.so
      - .libs/libsecp256k1.so.0.0.0
    organize:
      .libs/libsecp256k1.so: usr/lib/libsecp256k1.so
      .libs/libsecp256k1.so.0.0.0: usr/lib/libsecp256k1.so.0.0.0

  linda-icon:
    plugin: dump
    source: icons
    organize:
      lindacoin-wallet1.png: usr/share/lindacoin-wallet1.png
      lindacoin-wallet1.svg: usr/share/lindacoin-wallet1.svg

